# Generated by Django 3.0.3 on 2020-02-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20200212_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='name',
            new_name='group_name',
        ),
    ]
